import javax.swing.*;
public class RegisterPanel extends JFrame{
    JLayeredPane pane;
    JPanel bottomPanel;
    JLabel imageLabel, userLabel, passwordLabel, passwordAgainLabel;
    JTextField userName;
    JPasswordField  password;
    JPasswordField  passwordAgain;
    JButton register,checkPeople,returnHandIn;
    ImageIcon image;
    RegisterHandle handle;
	
    public RegisterPanel() {
        this.setTitle("新用户注册");
        pane = new JLayeredPane(); 
        userName = new JTextField(15);
        password=new JPasswordField(15);
        passwordAgain=new JPasswordField(15);
        image = new ImageIcon("src//2.JPG");
        imageLabel = new JLabel(image);
        userLabel = new JLabel("用户名：");
        passwordLabel = new JLabel("密码：");
        passwordAgainLabel = new JLabel("确认密码：");
        register = new JButton("注册");
        checkPeople = new JButton("以管理员身份查看注册表");
        returnHandIn= new JButton("登录界面");
        bottomPanel = (JPanel)this.getContentPane();
        bottomPanel.add(imageLabel);
        bottomPanel.setBounds(0, 0, image.getIconWidth(), image.getIconHeight());
        pane.add(userLabel,JLayeredPane.MODAL_LAYER);
        userLabel.setBounds(135, 110, 150, 40);
        pane.add(userName,JLayeredPane.MODAL_LAYER);
        userName.setBounds(190, 110, 200,40);
        pane.add(passwordLabel,JLayeredPane.MODAL_LAYER);
        passwordLabel.setBounds(145, 155, 150, 40);
        pane.add(password,JLayeredPane.MODAL_LAYER);
        password.setBounds(190,155, 200, 40);
        pane.add(passwordAgainLabel,JLayeredPane.MODAL_LAYER);
        passwordAgainLabel.setBounds(120, 200, 150, 40);
        pane.add(passwordAgain,JLayeredPane.MODAL_LAYER);
        passwordAgain.setBounds(190,200, 200, 40);
        pane.add(register,JLayeredPane.MODAL_LAYER);
        register.setBounds(190, 250, 200, 40);
        pane.add(returnHandIn,JLayeredPane.MODAL_LAYER);
       returnHandIn.setBounds(0, 0, 90, 50);
        pane.add(checkPeople, JLayeredPane.MODAL_LAYER);
        checkPeople.setBounds(320, 410, 180, 20);
        pane.add(bottomPanel,JLayeredPane.DEFAULT_LAYER);
        this.setBounds(600, 300,image.getIconWidth(),image.getIconHeight());
        this.setResizable(false);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLayeredPane(pane);
        this.setVisible(true);
        validate();
		handle = new RegisterHandle();
        register.addActionListener(handle);
        returnHandIn.addActionListener(handle);
        checkPeople.addActionListener(handle);
        handle.setView(this);
    }
}